main:
  cache_dir: ./cache

database:
  driver: postgres
  data_source_name: host=localhost port=5432 user=postgres password=hazem1999 dbname=sec_project sslmode=disable
  database_string: postgres://postgres:hazem1999@localhost:5432/sec_project?sslmode=disable