database:
  driver: postgres
  data_source_name: host=localhost port=5432 user=postgres password=postgres dbname=sec_project sslmode=disable
  database_string: postgres://postgres:postgres@localhost:5432/sec_project?sslmode=disable
  cache_dir: ./cache