---
- hosts: all
  remote_user: root
  become: yes
  tasks:
    - name: Apt Upgrade
      apt:
        upgrade: "yes"
        update_cache: yes
        cache_valid_time: 432000
    - name: Install Software Properties Common
      apt:
        name:
          - software-properties-common
    - name: Add Apt Key
      ansible.builtin.apt_key:
        id: C99B11DEB97541F0
        keyserver: keyserver.ubuntu.com
    - name: Add Golang Backports
      ansible.builtin.apt_repository:
        repo: 'deb http://ppa.launchpad.net/longsleep/golang-backports/ubuntu focal main'
        state: present
        update_cache: true
    - name: Add Golang Packages Repository
      ansible.builtin.apt_repository:
        repo: 'deb https://cli.github.com/packages stable main'
    - name: Install Packages
      apt:
        force: yes
        name:
          - postgresql
          - golang-go
          - git
          - make
          - vim
          - tig
          - ncdu
          - htop
          - tmux
          - jq
          - curl
          - gh