---
- hosts: "{{ host_names | default('all')}}"
  become: yes
  vars:
      ansible_ssh_user: "{{ ssh_user | default('root')}}"
      postgresql_data_dir: /mnt/sec/db
      postgresql_global_config_options:
        - option: data_directory
          value: "/mnt/sec/db"
  tasks:
    - name: Create SEC User
      become: yes
      become_user: root
      become_method: sudo
      user: name=sec state=present groups="sudo"
    - name: Update Golang From Apt
      become: yes
      become_user: root
      become_method: sudo
      ansible.builtin.apt_repository:
        repo: ppa:longsleep/golang-backports
    - name: Update Postgres From Apt
      become: yes
      become_user: root
      become_method: sudo
      ansible.builtin.apt_repository:
        update_cache: no
        repo: "deb http://apt.postgresql.org/pub/repos/apt focal-pgdg main"
        state: present
    - name: Add Postgres Key
      become: yes
      become_user: root
      become_method: sudo
      ansible.builtin.apt_key:
        url: https://www.postgresql.org/media/keys/ACCC4CF8.asc
        state: present
    - name: Install Necessities
      become: yes
      become_user: root
      become_method: sudo
      apt:
        update_cache: yes
        name:
          - software-properties-common
          - postgresql-14
          - python3
          - git
          - make
          - vim
          - tig
          - ncdu
          - htop
          - tmux
          - jq
          - curl     
          - acl
          - python3-pip
          - python3-psycopg2     
          - golang-go
    - name: Create /mnt/sec/db Directory
      become: yes
      become_user: root
      become_method: sudo
      file:
        path: /mnt/sec/db
        state: directory
        owner: sec
    - name: Get /mnt/sec/db Directory Data
      become: yes
      become_user: sec
      become_method: sudo
      shell: ls -la
      args: 
        chdir: /mnt/sec/db
      register: db_dir
    - name: InitDB in /mnt/sec/db
      become: yes
      become_user: sec
      command: /usr/lib/postgresql/14/bin/initdb -D /mnt/sec/db
      when: db_dir["stdout_lines"] | length <= 8
    - name: Create SEC User in DB
      become_user: postgres
      postgresql_user:
        login_user: postgres
        name: sec
        role_attr_flags: SUPERUSER
    - name: Create the Database
      become_user: postgres
      postgresql_db:
        name: sec
        owner: sec
        template: template0
        encoding: UTF8
        lc_collate: 'en_US.UTF-8'
        lc_ctype: 'en_US.UTF-8'
      when: db_dir["stdout_lines"] | length <= 8
    - name: Add Github Actions Public SSH
      become: yes
      become_user: root
      become_method: sudo
      blockinfile:
        path: /home/sec/.ssh/authorized_keys
        block: "{{ lookup('file', './ssh_deploy_keys/ssh_deploy_key.pub') }}"
