---
- hosts: "{{ host_names | default('all')}}"
  become: yes
  vars:
      ansible_ssh_user: "{{ ssh_user | default('root')}}"
      postgresql_data_dir: "/mnt/sec"
      postgresql_global_config_options:
        - option: data_directory
          value: "/mnt/sec"
  tasks:
    - name: Apt Upgrade
      become: yes
      become_user: root
      become_method: sudo
      apt:
        upgrade: "yes"
        update_cache: yes
        cache_valid_time: 432000
    - name: Install Software Properties Common
      apt:
        name:
          - software-properties-common
    - name: Install Necessities
      become: yes
      become_user: root
      become_method: sudo
      apt:
        update_cache: yes
        name:
          - python3
          - git
          - make
          - vim
          - tig
          - ncdu
          - htop
          - tmux
          - jq
          - curl
          - postgresql
          - postgresql-contrib
          - libpq-dev
          - python3-pip
          - python-psycopg2
          - golang-go
    - name: Get File Stat For /mnt/sec
      stat:
        path: /mnt/sec
      register: mnt_sec_stat
    - name: Create /mnt/sec Directory
      file:
        path: /mnt/sec
        state: directory
        owner: vagrant
      when: not mnt_sec_stat.stat.exists
    - name: Export Essential Variables
      shell: "export LC_CTYPE=en_US.UTF-8; export LC_ALL=en_US.UTF-8"
    - name: Get Database Folder
      command: du -sk /mnt/sec
      register: folder_size_raw
    - name: Get Database Folder Size
      set_fact:
        folder_size: "{{ folder_size_raw.stdout.split()[0] }}"
      when: mnt_sec_stat.stat.exists
    - name: Get /mnt/sec Content
      shell: ls -la
      args:
        chdir: /mnt/sec
      register: contents
      when: mnt_sec_stat.stat.exists
    - meta: end_play
      when: mnt_sec_stat.stat.exists and contents["stdout_lines"] | length > 8 and folder_size|int < 4000000000000
    - name: InitDB in /mnt/sec
      become: yes
      become_user: vagrant
      command: /usr/lib/postgresql/9.3/bin/initdb -D /mnt/sec
    - name: Export PG Data Directory
      shell: "export PGDATA=/mnt/sec"
    - name: Change Postgres File Permissions
      file:
        path: /var/run/postgresql/
        owner: vagrant
    - name: Start Postgres Cluster
      become: yes
      become_user: vagrant
      shell: /usr/lib/postgresql/9.3/bin/pg_ctl -D /mnt/sec/ start
    - name: Create Postgres User
      postgresql_user:
        login_user: vagrant
        db: postgres
        name: postgres
        role_attr_flags: SUPERUSER
    - name: Create the Database
      become_user: vagrant
      postgresql_db:
        name: vagrant
        owner: vagrant
        template: template0
        encoding: UTF8
        lc_collate: 'en_US.UTF-8'
        lc_ctype: 'en_US.UTF-8'