---
- hosts: "{{ host_names | default('all')}}"
  become: yes
  vars:
      ansible_ssh_user: "{{ ssh_user | default('root')}}"
      postgresql_data_dir: "/mnt/sec"
      postgresql_global_config_options:
        - option: data_directory
          value: "/mnt/sec"
  tasks:
    - name: Apt Upgrade
      become: yes
      become_user: root
      become_method: sudo
      apt:
        upgrade: "yes"
        update_cache: yes
        cache_valid_time: 432000
    - name: Install Software Properties Common
      apt:
        name:
          - software-properties-common
    - name: Install Necessities
      become: yes
      become_user: root
      become_method: sudo
      apt:
        update_cache: yes
        name:
          - python3
          - git
          - make
          - vim
          - tig
          - ncdu
          - htop
          - tmux
          - jq
          - curl
          - postgresql
          - postgresql-contrib
          - libpq-dev
          - python3-pip
          - python-psycopg2
          - snapd
    - name: Reboot To Configure Snap Properly
      reboot:
    - name: Install GH
      become: yes
      become_user: root
      become_method: sudo
      snap:
        name: gh
    - name: Install Golang
      become: yes
      become_user: root
      become_method: sudo
      snap:
        classic: yes
        name: go
    - name: Create /mnt/sec Directory
      file:
        path: /mnt/sec
        state: directory
        owner: postgres
    - name: InitDB in /mnt/sec
      become: yes
      become_user: postgres
      become_method: sudo
      command: postgresql-setup initdb
    - name: Start Postgres Cluster
      become: yes
      become_user: root
      become_method: sudo
      shell: /etc/init.d/postgresql start
    - name: Create the Database
      become_user: postgres
      postgresql_db:
        name: postgres
        owner: postgres
        template: template0
        encoding: UTF8
        lc_collate: 'en_US.UTF-8'
        lc_ctype: 'en_US.UTF-8'