CREATE TABLE mfd.txt (
    id serial PRIMARY KEY,
    adsh text,
    tag text,
    version text,
    ddate text,
    lang text,
    series text,
    class text,
    measure text,
    document text,
    otherdims text,
    iprx text,
    dcml text,
    escaped text,
    srclen text,
    txtlen text,
    footnote text,
    footlen text,
    context text,
    value text,
    created_at timestamp with time zone,
    updated_at timestamp with time zone,
    deleted_at timestamp with time zone,
    CONSTRAINT txt_unique_keys UNIQUE (adsh, tag, version, ddate, series, class, measure, document, otherdims, iprx),
    FOREIGN KEY (tag, version) REFERENCES mfd.tag (tag, version)
);