CREATE TABLE sec.secItemFile (
    id serial PRIMARY KEY,
    title text,
    link text,
    guid text,
    enclosure_url text,
    enclosure_length integer,
    enclosure_type text,
    description text,
    pubDate timestamp with time zone,
    companyName text,
    formType text,
    fillingDate timestamp with time zone,
    cikNumber integer,
    accessionNumber text,
    fileNumber text,
    acceptanceDatetime text,
    period text,
    assistantDirector text,
    assignedSic integer,
    fiscalYearEnd integer,
    xbrlSequence integer,
    xbrlFile text,
    xbrlType text,
    xbrlSize integer,
    xbrlDescription text,
    xbrlInlineXBRL bool,
    xbrlUrl text,

    created_at timestamp with time zone,
    updated_at timestamp with time zone,
    deleted_at timestamp with time zone,
    CONSTRAINT xbrl_file UNIQUE (xbrlSequence, xbrlFile, xbrlType, xbrlSize, xbrlDescription, xbrlInlineXBRL, xbrlUrl),
    CONSTRAINT fk_cik FOREIGN KEY (cikNumber) REFERENCES sec.ciks(cik)
);