CREATE TABLE mfd.sub (
    id serial PRIMARY KEY,
    adsh text,
    cik integer,
    name text,
    countryba text,
    stprba text,
    cityba text,
    zipba text,
    bas1 text,
    bas2 text,
    baph text,
    countryma text,
    strpma text,
    cityma text,
    zipma text,
    mas1 text,
    mas2 text,
    countryinc text,
    stprinc text,
    ein text,
    former text,
    changed text,
    fye text,
    pdate text,
    effdate text,
    form text,
    filed text,
    accepted timestamp,
    instance text,
    nciks text,
    aciks text,
    created_at timestamp with time zone,
    updated_at timestamp with time zone,
    deleted_at timestamp with time zone,
    CONSTRAINT adsh_key UNIQUE (adsh),
    CONSTRAINT fk_cik FOREIGN KEY (cik) REFERENCES sec.ciks(cik)
);