CREATE TABLE mfd.num (
    id serial PRIMARY KEY,
    adsh text,
    tag text,
    version text,
    ddate text,
    uom text,
    series text,
    class text,
    measure text,
    document text,
    otherdims text,
    iprx text,
    value text,
    footnote text,
    footlen text,
    dimn text,
    dcml text,
    created_at timestamp with time zone,
    updated_at timestamp with time zone,
    deleted_at timestamp with time zone,
    CONSTRAINT unique_keys UNIQUE (adsh, tag, version, ddate, uom, series, class, measure, document, otherdims, iprx),
    FOREIGN KEY (tag, version) REFERENCES mfd.tag (tag, version)
);