CREATE TABLE sec.sub (
    id serial PRIMARY KEY,
    adsh text,
    cik integer,
    name text,
    sic text,
    countryba text,
    stprba text,
    cityba text,
    zipba text,
    bas1 text,
    bas2 text,
    baph text,
    countryma text,
    strpma text,
    cityma text,
    zipma text,
    mas1 text,
    mas2 text,
    countryinc text,
    stprinc text,
    ein text,
    former text,
    changed text,
    afs text,
    wksi text,
    fye text,
    form text,
    period date,
    fy text,
    fp text,
    filled date,
    accepted timestamp,
    prevrpt text,
    detail text,
    instance text,
    nciks text,
    aciks text,
    created_at timestamp with time zone,
    updated_at timestamp with time zone,
    deleted_at timestamp with time zone,
    CONSTRAINT sub_item UNIQUE (adsh, cik, name, sic),
    CONSTRAINT fk_cik FOREIGN KEY (cik) REFERENCES sec.ciks(cik)
);