main:
  baseurl: https://www.sec.gov
  cachedir: ./cache
  ratelimitms: "100" 
	retrylimit: "3"

database:
  driver: postgres
  host: localhost
  port: 5432
  name: sec_project
  password: test_postgres
  user: test_postgres