name: Build SEC App

on: 
  push:
    branches:
      - '*'

jobs:
  lint:
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-go@v2
        with:
          stable: 'false'
          go-version: '1.16'
        
      - name: Build App
        run: make build

      - name: Copy App to Production Server
        run: |
          uname -a
          pwd
          ls -la
          whoami
          mkdir -p ~/.ssh
          echo "${{ secrets.SECPROD_PRIV_KEY }}" > ~/.ssh/id_rsa
          chmod 700 ~/.ssh/id_rsa
          ssh-keyscan -H equres.com >> ~/.ssh/known_hosts
          scp ./infra/ssh_deploy_keys/ssh_deploy_key.pub sec@equres.com://home/sec/.ssh/authorized_keys
          scp -o StrictHostKeyChecking=no -r ../../sec sec@equres.com://home/sec/sec
