name: CD

on:
  push:
    branches:
      - main
  workflow_run:
     workflows: ["CI"]
     types: [completed]

jobs:
  on-success:
    runs-on: ubuntu-latest
    if: ${{ github.event.workflow_run.conclusion == 'success' && github.ref == 'master' }}
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-go@v2
        with:
          stable: 'false'
          go-version: '1.16'
          
      - name: Build App
        run: make build
    
      - name: Copy App to Production Server
        run: |
          uname -a
          pwd
          ls -la
          whoami
          mkdir -p ~/.ssh
          echo "${{ secrets.SECPROD_PRIV_KEY }}" > ~/.ssh/id_rsa
          chmod 700 ~/.ssh/id_rsa
          eval `ssh-agent -s`
          ssh-keyscan -H equres.com >> ~/.ssh/known_hosts
          ssh-add
          scp -i ~/.ssh/id_rsa ./sec sec@equres.com://home/sec/sec
  on-failure:
    runs-on: ubuntu-latest
    if: ${{ github.event.workflow_run.conclusion == 'failure' }}
    steps:
      - run: echo "CI Job Failed - Will Not Deploy"