name: CD

on:
  workflow_run:
    workflows: ["CI"]
    branches: [*]
    types: [completed]

jobs:
  on-success:
    runs-on: ubuntu-latest
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-go@v2
        with:
          stable: 'false'
          go-version: '1.16'
          
      - name: Build App
        run: make build
    
      - name: Copy App to Production Server
        run: |
          uname -a
          pwd
          ls -la
          whoami
          mkdir -p ~/.ssh
          echo "${{ secrets.SECPROD_PRIV_KEY }}" > ~/.ssh/id_rsa
          chmod 700 ~/.ssh/id_rsa
          eval `ssh-agent -s`
          ssh-keyscan -H equres.com >> ~/.ssh/known_hosts
          ssh-add
          ssh -i ~/.ssh/id_rsa sec@equres.com mv sec sec.old
          scp -i ~/.ssh/id_rsa ./sec sec@equres.com://home/sec/sec