name: Lint SEC App

on: 
  push:
    branches:
      - '*'

jobs:
  lint:
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-go@v2
        with:
          stable: 'false'
          go-version: '1.16'
        
      - name: Clean Up Code
        run: make clean
