name: PostgreSQL DB
on: 
  push:
      branches:
        - '*'
jobs:
  postgres-job:
    runs-on: ubuntu-latest
    services:
      postgres:
        image: postgres:latest
        env:
          POSTGRES_HOST: localhost
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres
          POSTGRES_DB: sec_project
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
        ports:
          - 5432:5432

    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-go@v2
        with:
          stable: 'false'
          go-version: '1.16'
        
      - name: Build App
        run: make build

      - name: Run Migration
        run: make migrateup

      - name: Query database
        run: psql -U postgres -d sec_project -c "\dt sec."